# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: clojos_common/service/protobufs/teams_service/teams_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nAclojos_common/service/protobufs/teams_service/teams_service.proto\x12\x05teams\x1a\x1bgoogle/protobuf/empty.proto\" \n\x0cGetTeamQuery\x12\x10\n\x08teamName\x18\x01 \x01(\t\"=\n\rTeamsResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1c\n\x06result\x18\x02 \x01(\x0b\x32\x0c.teams.Teams\"#\n\x05Teams\x12\x1a\n\x05teams\x18\x01 \x03(\x0b\x32\x0b.teams.Team\"D\n\x04Team\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07subject\x18\x02 \x01(\t\x12\x1d\n\x07members\x18\x03 \x03(\x0b\x32\x0c.teams.Party\"N\n\x05Party\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rsymbolic_name\x18\x02 \x01(\t\x12\x14\n\x07subject\x18\x03 \x01(\tH\x00\x88\x01\x01\x42\n\n\x08_subject2J\n\x0cTeamsService\x12:\n\x08GetTeams\x12\x16.google.protobuf.Empty\x1a\x14.teams.TeamsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'clojos_common.service.protobufs.teams_service.teams_service_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_GETTEAMQUERY']._serialized_start=105
  _globals['_GETTEAMQUERY']._serialized_end=137
  _globals['_TEAMSRESPONSE']._serialized_start=139
  _globals['_TEAMSRESPONSE']._serialized_end=200
  _globals['_TEAMS']._serialized_start=202
  _globals['_TEAMS']._serialized_end=237
  _globals['_TEAM']._serialized_start=239
  _globals['_TEAM']._serialized_end=307
  _globals['_PARTY']._serialized_start=309
  _globals['_PARTY']._serialized_end=387
  _globals['_TEAMSSERVICE']._serialized_start=389
  _globals['_TEAMSSERVICE']._serialized_end=463
# @@protoc_insertion_point(module_scope)
